
name: Demo CICD workflow

on:
  # Manual click (deliver) workflow whenever user needs
  workflow_dispatch:

# these are jobs inside the workflow
jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        step: echo "Code Clone"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        step: echo "docker build -t app:latest ."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test image and container
        step: echo "sonarqube"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        step: echo "docker compose deploy app"









