
name: Demo CICD workflow

# Manual click (deliver) workflow whenever user needs
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment value
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - stg

# these are jobs inside the workflow.
jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "Code Clone"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker Image
        run: echo "docker build -t app:latest ."

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test image and container
        run: echo "sonarqube"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        run: echo "docker compose deploy app"









