name: Deploy flask app

on:
    workflow_dispatch:
        
jobs:
    deploy:
        runs-on: self-hosted

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Deploy with docker compose
          run: docker compose up -d --build