name: Deploy flask app

on:
    workflow_run:              # Auto trigger workflow by using workflows_run
        workflows: ["Docker Build and Push"]   # Name of docker-build-push.yml workflow
        types: [completed]
        branches:
            - main

jobs:
   
    deploy:
        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}

        runs-on: self-hosted

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set up Docker compose 
              uses: docker/setup-compose-action@v2 

            - name: Deploy with docker compose
              run: docker compose up -d --build
