name: Demo workflow

# on:
#   push:
#     branches: [main]

on:
  workflow_dispatch:

jobs:

  code:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout code
        run: echo "Code clone"

  build:
    needs: [code]
    runs-on: ubuntu-latest
    steps:
      - name: Docker build
        run: echo "docker build -t app ."

  test:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test code
        run: echo "Test code"

  deploy:     
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code
        run: echo "docker compose up or down"